#!/usr/bin/env node

/**
 * Generate Firebase Messaging Service Worker
 * This script reads Firebase config from .env.local and generates the service worker file
 */

const fs = require('fs');
const path = require('path');

// Load environment variables from .env.local
function loadEnvFile() {
  const envPath = path.join(__dirname, '..', '.env.local');
  
  if (!fs.existsSync(envPath)) {
    console.error('❌ Error: .env.local file not found');
    console.log('Please create .env.local with your Firebase configuration');
    process.exit(1);
  }

  const envContent = fs.readFileSync(envPath, 'utf8');
  const env = {};

  envContent.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const [key, ...valueParts] = trimmed.split('=');
      const value = valueParts.join('=').trim();
      env[key] = value;
    }
  });

  return env;
}

// Generate service worker content
function generateServiceWorker(env) {
  const apiKey = env.NEXT_PUBLIC_FIREBASE_API_KEY;
  const authDomain = env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN;
  const projectId = env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;
  const storageBucket = env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET;
  const messagingSenderId = env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID;
  const appId = env.NEXT_PUBLIC_FIREBASE_APP_ID;
  const measurementId = env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID; // Optional

  // Validate required fields
  const missing = [];
  if (!apiKey) missing.push('NEXT_PUBLIC_FIREBASE_API_KEY');
  if (!authDomain) missing.push('NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN');
  if (!projectId) missing.push('NEXT_PUBLIC_FIREBASE_PROJECT_ID');
  if (!storageBucket) missing.push('NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET');
  if (!messagingSenderId) missing.push('NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID');
  if (!appId) missing.push('NEXT_PUBLIC_FIREBASE_APP_ID');

  if (missing.length > 0) {
    console.error('❌ Error: Missing required Firebase configuration:');
    missing.forEach(key => console.error(`   - ${key}`));
    process.exit(1);
  }

  // Build config object
  let configLines = `  apiKey: "${apiKey}",
  authDomain: "${authDomain}",
  projectId: "${projectId}",
  storageBucket: "${storageBucket}",
  messagingSenderId: "${messagingSenderId}",
  appId: "${appId}"`;

  // Add measurementId if provided
  if (measurementId) {
    configLines += `,
  measurementId: "${measurementId}"`;
  }

  return `// Firebase Cloud Messaging Service Worker
// This file is auto-generated from .env.local by scripts/generate-sw.js
// DO NOT EDIT THIS FILE MANUALLY - Run 'npm run generate:sw' instead

importScripts('https://www.gstatic.com/firebasejs/10.8.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.8.0/firebase-messaging-compat.js');

// Initialize Firebase in the service worker
firebase.initializeApp({
${configLines}
});

const messaging = firebase.messaging();

// Handle background messages
messaging.onBackgroundMessage((payload) => {
  console.log('[firebase-messaging-sw.js] Received background message', payload);

  const notificationTitle = payload.notification?.title || 'New Notification';
  const notificationOptions = {
    body: payload.notification?.body || '',
    icon: '/icon-192x192.png',
    badge: '/badge-72x72.png',
    tag: payload.data?.conversationId || 'default',
    data: payload.data,
    requireInteraction: false,
    actions: [
      {
        action: 'view',
        title: 'View',
      },
      {
        action: 'close',
        title: 'Close',
      }
    ]
  };

  return self.registration.showNotification(notificationTitle, notificationOptions);
});

// Handle notification click
self.addEventListener('notificationclick', (event) => {
  console.log('[firebase-messaging-sw.js] Notification clicked', event);

  event.notification.close();

  const action = event.action;
  const notificationData = event.notification.data;

  if (action === 'close') {
    return;
  }

  // Open the app or navigate to specific page
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // If there's an open window, focus it
      for (const client of clientList) {
        if (client.url === '/' && 'focus' in client) {
          return client.focus();
        }
      }

      // Otherwise open a new window
      if (clients.openWindow) {
        let url = '/';

        // Navigate to specific page based on notification data
        if (notificationData?.conversationId) {
          url = \`/chat/\${notificationData.conversationId}\`;
        } else if (notificationData?.appointmentId) {
          url = \`/appointments/\${notificationData.appointmentId}\`;
        }

        return clients.openWindow(url);
      }
    })
  );
});
`;
}

// Main execution
try {
  console.log('🔧 Generating Firebase Messaging Service Worker...\n');

  const env = loadEnvFile();
  console.log('✅ Loaded environment variables from .env.local');

  const swContent = generateServiceWorker(env);
  const swPath = path.join(__dirname, '..', 'public', 'firebase-messaging-sw.js');

  fs.writeFileSync(swPath, swContent, 'utf8');
  console.log('✅ Generated service worker at public/firebase-messaging-sw.js');

  console.log('\n📋 Configuration:');
  console.log(`   Project ID: ${env.NEXT_PUBLIC_FIREBASE_PROJECT_ID}`);
  console.log(`   Auth Domain: ${env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}`);
  console.log(`   Storage Bucket: ${env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}`);
  console.log(`   Messaging Sender ID: ${env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}`);
  if (env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID) {
    console.log(`   Measurement ID: ${env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}`);
  }

  console.log('\n✨ Done! You can now run your Next.js app.');
  console.log('   Make sure NEXT_PUBLIC_FIREBASE_VAPID_KEY is also set in .env.local\n');

} catch (error) {
  console.error('❌ Error generating service worker:', error.message);
  process.exit(1);
}